# Generated by Django 5.2.8 on 2025-12-17 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tmdb_id", models.PositiveIntegerField(unique=True, verbose_name="TMDB ID")),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "original_name",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Оригинальное имя"),
                ),
                (
                    "profile_path",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Ссылка на фото"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tmdb_id", models.PositiveIntegerField(unique=True, verbose_name="TMDB ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tmdb_id", models.PositiveIntegerField(unique=True, verbose_name="TMDB ID")),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "original_name",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Оригинальное имя"),
                ),
                ("profile_path", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=500, verbose_name="Название")),
                ("tmdb_id", models.PositiveIntegerField(verbose_name="TMDB ID")),
                ("tagline", models.CharField(blank=True, max_length=255, null=True, verbose_name="Короткое описание")),
                (
                    "original_title",
                    models.CharField(blank=True, max_length=500, null=True, verbose_name="Оригинальное название"),
                ),
                ("overview", models.TextField(verbose_name="Описание")),
                (
                    "poster_path",
                    models.CharField(blank=True, max_length=250, null=True, verbose_name="Ссылка на постер"),
                ),
                ("backdrop_path", models.CharField(blank=True, max_length=255, null=True)),
                ("original_country", models.CharField(blank=True, max_length=100, null=True, verbose_name="Страна")),
                ("runtime", models.PositiveIntegerField(blank=True, null=True, verbose_name="Продолжительность")),
                ("release_date", models.DateField(blank=True, null=True, verbose_name="Дата выхода")),
                ("budget", models.CharField(blank=True, null=True, verbose_name="Бюджет")),
                ("revenue", models.CharField(blank=True, null=True, verbose_name="Мировые сборы")),
                ("production_company", models.CharField(blank=True, null=True, verbose_name="Производство")),
                ("vote_average", models.FloatField(blank=True, null=True, verbose_name="Средняя оценка")),
                ("vote_count", models.PositiveIntegerField(blank=True, null=True, verbose_name="Количество оценок")),
                ("is_watched", models.BooleanField(default=False, verbose_name="Просмотрено")),
                ("is_favourite", models.BooleanField(default=False, verbose_name="Любимое")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="films",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "фильм",
                "verbose_name_plural": "фильмы",
                "ordering": ["title", "-release_date"],
            },
        ),
        migrations.CreateModel(
            name="FilmActor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("character", models.CharField(blank=True, max_length=255, null=True, verbose_name="Роль")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Приоритет значимости в фильме")),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="films.actor")),
                ("film", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="films.film")),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="film",
            name="actors",
            field=models.ManyToManyField(
                blank=True, related_name="films", through="films.FilmActor", to="films.actor", verbose_name="Актеры"
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="genres",
            field=models.ManyToManyField(related_name="films", to="films.genre", verbose_name="Жанры"),
        ),
        migrations.CreateModel(
            name="FilmCrew",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("job", models.CharField(max_length=100)),
                ("film", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="films.film")),
                ("person", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="films.person")),
            ],
            options={
                "unique_together": {("film", "person", "job")},
            },
        ),
        migrations.AddField(
            model_name="film",
            name="crew",
            field=models.ManyToManyField(
                blank=True, related_name="films", through="films.FilmCrew", to="films.person"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="film",
            unique_together={("user", "tmdb_id")},
        ),
    ]
