# Generated by Django 5.2.8 on 2025-12-27 09:57

from django.db import migrations
from services.tmdb import Tmdb


def load_tmdb_genres(apps, schema_editor):
    Genre = apps.get_model("films", "Genre")
    tmdb = Tmdb()

    data = tmdb.get_genres() or {}
    for g in data.get("genres", []):
        Genre.objects.update_or_create(
            tmdb_id=g["id"],
            defaults={"name": g["name"]},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_tmdb_genres, migrations.RunPython.noop),
    ]
