# Generated by Django 5.2.8 on 2026-01-02 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0002_load_tmdb_genres"),
    ]

    operations = [
        migrations.RenameField(
            model_name="film",
            old_name="is_favourite",
            new_name="is_favorite",
        ),
    ]
