# Generated by Django 5.2.8 on 2026-01-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0003_rename_is_favourite_film_is_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="is_planned",
            field=models.BooleanField(default=False, verbose_name="Запланировано к просмотру"),
        ),
    ]
