# Generated by Django 5.2.8 on 2026-01-16 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0004_film_is_planned"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="film",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="film",
            name="tmdb_id",
            field=models.PositiveIntegerField(unique=True, verbose_name="TMDB ID"),
        ),
        migrations.RemoveField(
            model_name="film",
            name="is_favorite",
        ),
        migrations.RemoveField(
            model_name="film",
            name="is_planned",
        ),
        migrations.RemoveField(
            model_name="film",
            name="is_watched",
        ),
        migrations.RemoveField(
            model_name="film",
            name="user",
        ),
        migrations.CreateModel(
            name="UserFilm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_favorite", models.BooleanField(default=False, verbose_name="Любимое")),
                ("is_planned", models.BooleanField(default=False, verbose_name="Запланировано к просмотру")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="user_relations", to="films.film"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_films",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["user", "film"], name="films_userf_user_id_ea5352_idx")],
                "unique_together": {("user", "film")},
            },
        ),
    ]
