# Generated by Django 5.2.8 on 2026-01-24 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0005_alter_film_unique_together_alter_film_tmdb_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userfilm",
            name="is_planned",
        ),
    ]
