# Generated by Django 5.2.8 on 2026-01-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0006_remove_userfilm_is_planned"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userfilm",
            options={"permissions": [("view_user_films", "Может просматривать фильмы пользователей")]},
        ),
    ]
