# Generated by Django 5.2.8 on 2025-12-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_confirmed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="email_new",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="tg_chat_id",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="Telegram id"),
        ),
    ]
