# Generated by Django 5.2.8 on 2026-01-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_email_confirmed_customuser_email_new_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="Имя пользователя")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail пользователя")),
                ("message", models.TextField(max_length=2000, verbose_name="Сообщение пользователя")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
            ],
            options={
                "verbose_name": "обратная связь",
                "verbose_name_plural": "обратная связь",
                "ordering": ["name", "email", "created_at"],
            },
        ),
    ]
