# Generated by Django 5.2.8 on 2026-01-22 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("films", "0005_alter_film_unique_together_alter_film_tmdb_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("planned_date", models.DateField(verbose_name="Дата просмотра")),
                (
                    "status",
                    models.CharField(
                        choices=[("planned", "Запланирован"), ("watched", "Просмотрен"), ("skipped", "Пропущен")],
                        default="planned",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Комментарий")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="films.film",
                        verbose_name="Фильм",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "просмотр",
                "verbose_name_plural": "просмотры",
                "ordering": ["-planned_date"],
                "indexes": [
                    models.Index(fields=["user", "film"], name="calendar_ev_user_id_53421e_idx"),
                    models.Index(fields=["-planned_date", "film"], name="calendar_ev_planned_193081_idx"),
                ],
                "unique_together": {("user", "film")},
            },
        ),
    ]
