# Generated by Django 5.2.8 on 2026-01-22 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_events", "0001_initial"),
        ("films", "0005_alter_film_unique_together_alter_film_tmdb_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="calendarevent",
            name="calendar_ev_planned_193081_idx",
        ),
        migrations.AlterUniqueTogether(
            name="calendarevent",
            unique_together={("user", "film", "planned_date")},
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="reminder_sent",
            field=models.BooleanField(default=False, verbose_name="Отправлено"),
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(fields=["planned_date", "film"], name="calendar_ev_planned_e83ccf_idx"),
        ),
    ]
