# Generated by Django 5.2.8 on 2026-01-23 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_events", "0003_remove_calendarevent_calendar_ev_planned_e83ccf_idx_and_more"),
        ("films", "0005_alter_film_unique_together_alter_film_tmdb_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="calendarevent",
            name="calendar_ev_status_09589e_idx",
        ),
        migrations.RemoveField(
            model_name="calendarevent",
            name="status",
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(fields=["reminder_sent", "planned_date"], name="calendar_ev_reminde_9db341_idx"),
        ),
    ]
