# Generated by Django 5.2.8 on 2026-01-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_events", "0004_remove_calendarevent_calendar_ev_status_09589e_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calendarevent",
            options={
                "ordering": ["-planned_date"],
                "permissions": [("view_user_calendar", "Может видеть запланированные просмотры пользователей")],
                "verbose_name": "просмотр",
                "verbose_name_plural": "просмотры",
            },
        ),
    ]
