# Generated by Django 5.2.8 on 2026-01-12 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("films", "0003_rename_is_favourite_film_is_favorite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("watched_at", models.DateField(verbose_name="Дата просмотра")),
                ("user_rating", models.FloatField(verbose_name="Оценка")),
                ("number_of_views", models.PositiveIntegerField(blank=True, null=True, verbose_name="Просмотров")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="films.film",
                        verbose_name="Фильм",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "отзыв",
                "verbose_name_plural": "отзывы",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["user", "film"], name="reviews_rev_user_id_35fb13_idx"),
                    models.Index(fields=["-updated_at"], name="reviews_rev_updated_884e74_idx"),
                ],
                "unique_together": {("user", "film")},
            },
        ),
    ]
