# Generated by Django 5.2.8 on 2026-01-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="review",
            field=models.TextField(blank=True, verbose_name="Отзыв"),
        ),
    ]
