# Generated by Django 5.2.8 on 2026-01-19 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_review_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="acting_rating",
            field=models.FloatField(
                default=5,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
                verbose_name="Актеры",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="directing_rating",
            field=models.FloatField(
                default=5,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
                verbose_name="Режиссура",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="plot_rating",
            field=models.FloatField(
                default=5,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
                verbose_name="Сюжет",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="soundtrack_rating",
            field=models.FloatField(
                default=5,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
                verbose_name="Саундтрек",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="visuals_rating",
            field=models.FloatField(
                default=5,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
                verbose_name="Визуал",
            ),
        ),
    ]
