# Generated by Django 5.2.8 on 2026-01-19 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_review_acting_rating_review_directing_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="acting_rating",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
                verbose_name="Актеры",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="directing_rating",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
                verbose_name="Режиссура",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="plot_rating",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
                verbose_name="Сюжет",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="soundtrack_rating",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
                verbose_name="Саундтрек",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="visuals_rating",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
                verbose_name="Визуал",
            ),
        ),
    ]
