# Generated by Django 5.2.8 on 2026-01-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_alter_review_acting_rating_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-updated_at"],
                "permissions": [("view_user_reviews", "Может просматривать оценки и отзывы пользователей на фильмы")],
                "verbose_name": "отзыв",
                "verbose_name_plural": "отзывы",
            },
        ),
    ]
